"use strict"

module.exports = {
  url: "https://developer-diary.netlify.com",
  title: "",
  tagline: "",
  copyright: "© 2019 willjw3, All rights reserved",
  author: {
    name: "",
    bio: "",
    contacts: {
      linkedin: "",
      github: "",
      stackoverflow: "",
      freecodecamp: "#",
      twitter: "",
    },
  },
  labels: [
    {
      tag: "react",
      tech: "React",
      name: "DiReact",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "nodejs",
      tech: "Node.js",
      name: "DiNodejsSmall",
      size: 20,
      color: "lightgreen",
    },
    {
      tag: "git",
      tech: "Git",
      name: "DiGitMerge",
      size: 20,
      color: "white",
    },
    {
      tag: "javascript",
      tech: "JavaScript",
      name: "DiJsBadge",
      size: 20,
      color: "yellow",
    },
    {
      tag: "css",
      tech: "CSS",
      name: "DiCss3Full",
      size: 20,
      color: "teal",
    },
    {
      tag: "java",
      tech: "Java",
      name: "FaJava",
      size: 20,
      color: "wheat",
    },
    {
      tag: "html",
      tech: "HTML",
      name: "FaHtml5",
      size: 20,
      color: "darkorange",
    },
    {
      tag: "php",
      tech: "php",
      name: "DiPhp",
      size: 20,
      color: "violet",
    },
    {
      tag: "mongodb",
      tech: "MongoDB",
      name: "DiMongodb",
      size: 20,
      color: "green",
    },
    {
      tag: "vscode",
      tech: "VS Code",
      name: "DiVisualstudio",
      size: 20,
      color: "deepskyblue",
    },
  ],
}
